[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mumbai = "https://polygon-mumbai.infura.io/v3/87b04c4f63d44167aefe897951736197"
goerli = "https://goerli.infura.io/v3/${GOERLI_RPC_INFURA}"
sepolia = "https://sepolia.infura.io/v3/${SEPOLIA_RPC_INFURA}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
